version: '3'

services:
  gewechat:
    build: .
    container_name: gewechat-python
    restart: always
    ports:
      - "9912:9912"
    volumes:
      - .:/app
      - ./gewechat_client/config.yaml:/app/gewechat_client/config.yaml
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Shanghai
    command: python -m gewechat_client.main
    networks:
      - wechat_network
    tty: true
    stdin_open: true
    extra_hosts:
      - "gewe:172.20.0.4"

networks:
  wechat_network:
    external: true
